/*
 * Base de datos de alimentos de referencia (valores aproximados por 100 g/100 ml,
 * basados en el etiquetado habitual de productos similares de Mercadona (Hacendado)
 * y Lidl (Milbona, Vitasia, Alesto...). Son valores orientativos: revisa el envase
 * real cuando puedas y edita/añade alimentos desde la app si difieren.
 * kcal, protein, carbs, fat en gramos por 100 g o 100 ml.
 */
const SEED_FOODS = [
  // ---- Carnes y pescado ----
  { name: 'Pechuga de pollo fresca', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 110, protein: 23, carbs: 0, fat: 1.5 },
  { name: 'Contramuslo de pollo', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 152, protein: 18, carbs: 0, fat: 8.5 },
  { name: 'Pavo fileteado', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 104, protein: 24, carbs: 0.5, fat: 1 },
  { name: 'Lomo de cerdo fresco', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 130, protein: 22, carbs: 0, fat: 4.5 },
  { name: 'Carne picada mixta', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 216, protein: 18, carbs: 0, fat: 16 },
  { name: 'Solomillo de ternera', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 143, protein: 21, carbs: 0, fat: 6 },
  { name: 'Salmón fresco', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 190, protein: 20, carbs: 0, fat: 12 },
  { name: 'Atún en aceite de oliva (lata)', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 190, protein: 25, carbs: 0, fat: 10 },
  { name: 'Atún al natural (lata)', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 100, protein: 24, carbs: 0, fat: 0.8 },
  { name: 'Merluza congelada', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 85, protein: 18, carbs: 0, fat: 1 },
  { name: 'Gambas peladas congeladas', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 91, protein: 20, carbs: 0.5, fat: 1 },
  { name: 'Jamón cocido extra', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 104, protein: 18, carbs: 1, fat: 3 },
  { name: 'Jamón serrano', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 195, protein: 31, carbs: 0, fat: 8 },
  { name: 'Pechuga de pavo (fiambre)', brand: 'Hacendado', store: 'Mercadona', category: 'Carne y pescado', kcal: 90, protein: 19, carbs: 1, fat: 1 },
  { name: 'Pechuga de pollo fresca', brand: 'Meatlovers', store: 'Lidl', category: 'Carne y pescado', kcal: 109, protein: 23, carbs: 0, fat: 1.3 },
  { name: 'Salmón fresco', brand: 'Nixe', store: 'Lidl', category: 'Carne y pescado', kcal: 188, protein: 20, carbs: 0, fat: 12 },
  { name: 'Atún claro en aceite (lata)', brand: 'Eugenio', store: 'Lidl', category: 'Carne y pescado', kcal: 189, protein: 24, carbs: 0, fat: 10 },
  { name: 'Jamón cocido', brand: 'Meatlovers', store: 'Lidl', category: 'Carne y pescado', kcal: 100, protein: 17, carbs: 1.5, fat: 3 },
  { name: 'Carne picada de vacuno', brand: 'Meatlovers', store: 'Lidl', category: 'Carne y pescado', kcal: 210, protein: 19, carbs: 0, fat: 15 },
  { name: 'Varitas de merluza', brand: 'Fishy', store: 'Lidl', category: 'Carne y pescado', kcal: 180, protein: 12, carbs: 16, fat: 8 },

  // ---- Huevos y lácteos ----
  { name: 'Huevos frescos (M)', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 148, protein: 12.5, carbs: 0.5, fat: 10.5 },
  { name: 'Leche desnatada', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 35, protein: 3.4, carbs: 4.9, fat: 0.2 },
  { name: 'Leche semidesnatada', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 46, protein: 3.2, carbs: 4.8, fat: 1.6 },
  { name: 'Leche entera', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 65, protein: 3.2, carbs: 4.7, fat: 3.6 },
  { name: 'Bebida de avena', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 47, protein: 0.4, carbs: 8, fat: 1.5 },
  { name: 'Yogur natural', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 61, protein: 3.6, carbs: 4.7, fat: 3.2 },
  { name: 'Yogur griego natural', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 97, protein: 3.8, carbs: 4.5, fat: 7 },
  { name: 'Yogur griego 0%', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 57, protein: 5.8, carbs: 4.1, fat: 1.5 },
  { name: 'Skyr natural', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 63, protein: 11, carbs: 4, fat: 0.2 },
  { name: 'Queso fresco batido 0%', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 47, protein: 8, carbs: 3.9, fat: 0.2 },
  { name: 'Requesón', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 96, protein: 13, carbs: 3.5, fat: 3.5 },
  { name: 'Queso cottage', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 98, protein: 11, carbs: 3.4, fat: 4.3 },
  { name: 'Queso curado', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 402, protein: 26, carbs: 0.5, fat: 33 },
  { name: 'Queso en lonchas light', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 220, protein: 28, carbs: 2, fat: 11 },
  { name: 'Mozzarella rallada', brand: 'Hacendado', store: 'Mercadona', category: 'Huevos y lácteos', kcal: 280, protein: 22, carbs: 2, fat: 20 },
  { name: 'Huevos frescos (M)', brand: 'Vitalia', store: 'Lidl', category: 'Huevos y lácteos', kcal: 149, protein: 12.6, carbs: 0.5, fat: 10.6 },
  { name: 'Leche desnatada', brand: 'Milbona', store: 'Lidl', category: 'Huevos y lácteos', kcal: 34, protein: 3.4, carbs: 4.8, fat: 0.1 },
  { name: 'Leche semidesnatada', brand: 'Milbona', store: 'Lidl', category: 'Huevos y lácteos', kcal: 47, protein: 3.3, carbs: 4.8, fat: 1.6 },
  { name: 'Yogur natural', brand: 'Milbona', store: 'Lidl', category: 'Huevos y lácteos', kcal: 62, protein: 3.5, carbs: 4.9, fat: 3.3 },
  { name: 'Yogur griego', brand: 'Milbona', store: 'Lidl', category: 'Huevos y lácteos', kcal: 133, protein: 3.6, carbs: 4.6, fat: 11 },
  { name: 'Skyr natural', brand: 'Milbona', store: 'Lidl', category: 'Huevos y lácteos', kcal: 62, protein: 11.5, carbs: 3.9, fat: 0.3 },
  { name: 'Queso fresco batido', brand: 'Milbona', store: 'Lidl', category: 'Huevos y lácteos', kcal: 74, protein: 7, carbs: 4, fat: 3 },
  { name: 'Queso mozzarella', brand: 'Milbona', store: 'Lidl', category: 'Huevos y lácteos', kcal: 260, protein: 21, carbs: 1, fat: 19 },
  { name: 'Mantequilla', brand: 'Milbona', store: 'Lidl', category: 'Huevos y lácteos', kcal: 740, protein: 0.6, carbs: 0.6, fat: 82 },

  // ---- Cereales, pasta, arroz y panadería ----
  { name: 'Arroz redondo', brand: 'Hacendado', store: 'Mercadona', category: 'Cereales y legumbres', kcal: 354, protein: 7, carbs: 79, fat: 0.6 },
  { name: 'Arroz basmati', brand: 'Hacendado', store: 'Mercadona', category: 'Cereales y legumbres', kcal: 349, protein: 7.5, carbs: 77, fat: 0.7 },
  { name: 'Arroz integral', brand: 'Hacendado', store: 'Mercadona', category: 'Cereales y legumbres', kcal: 348, protein: 7.5, carbs: 74, fat: 2.5 },
  { name: 'Pasta espagueti', brand: 'Hacendado', store: 'Mercadona', category: 'Cereales y legumbres', kcal: 353, protein: 12, carbs: 71, fat: 1.5 },
  { name: 'Pasta integral', brand: 'Hacendado', store: 'Mercadona', category: 'Cereales y legumbres', kcal: 345, protein: 13, carbs: 63, fat: 2.5 },
  { name: 'Copos de avena', brand: 'Hacendado', store: 'Mercadona', category: 'Cereales y legumbres', kcal: 367, protein: 13, carbs: 58, fat: 7 },
  { name: 'Quinoa', brand: 'Hacendado', store: 'Mercadona', category: 'Cereales y legumbres', kcal: 368, protein: 14, carbs: 64, fat: 6 },
  { name: 'Cuscús', brand: 'Hacendado', store: 'Mercadona', category: 'Cereales y legumbres', kcal: 376, protein: 12.8, carbs: 77, fat: 1.1 },
  { name: 'Pan de molde blanco', brand: 'Hacendado', store: 'Mercadona', category: 'Panadería', kcal: 250, protein: 8, carbs: 47, fat: 3 },
  { name: 'Pan de molde integral', brand: 'Hacendado', store: 'Mercadona', category: 'Panadería', kcal: 235, protein: 9, carbs: 41, fat: 3.5 },
  { name: 'Pan de molde proteico', brand: 'Hacendado', store: 'Mercadona', category: 'Panadería', kcal: 220, protein: 20, carbs: 24, fat: 5 },
  { name: 'Tortitas de maíz', brand: 'Hacendado', store: 'Mercadona', category: 'Cereales y legumbres', kcal: 383, protein: 8, carbs: 81, fat: 2.8 },
  { name: 'Tortitas de arroz', brand: 'Hacendado', store: 'Mercadona', category: 'Cereales y legumbres', kcal: 387, protein: 8, carbs: 82, fat: 3 },
  { name: 'Tortillas de trigo', brand: 'Hacendado', store: 'Mercadona', category: 'Panadería', kcal: 300, protein: 8, carbs: 50, fat: 7 },
  { name: 'Patata', brand: 'Hacendado', store: 'Mercadona', category: 'Fruta y verdura', kcal: 77, protein: 2, carbs: 17, fat: 0.1 },
  { name: 'Boniato', brand: 'Hacendado', store: 'Mercadona', category: 'Fruta y verdura', kcal: 86, protein: 1.6, carbs: 20, fat: 0.1 },
  { name: 'Arroz basmati', brand: 'Vitasia', store: 'Lidl', category: 'Cereales y legumbres', kcal: 350, protein: 7.3, carbs: 78, fat: 0.6 },
  { name: 'Pasta espagueti', brand: 'Combino', store: 'Lidl', category: 'Cereales y legumbres', kcal: 355, protein: 12.5, carbs: 70, fat: 1.5 },
  { name: 'Copos de avena', brand: 'Alesto', store: 'Lidl', category: 'Cereales y legumbres', kcal: 372, protein: 12.5, carbs: 59, fat: 7.2 },
  { name: 'Pan de molde integral', brand: 'Vitasia', store: 'Lidl', category: 'Panadería', kcal: 230, protein: 9, carbs: 40, fat: 3.2 },
  { name: 'Quinoa', brand: 'Vitasia', store: 'Lidl', category: 'Cereales y legumbres', kcal: 370, protein: 13.5, carbs: 65, fat: 6.1 },

  // ---- Legumbres ----
  { name: 'Garbanzos cocidos', brand: 'Hacendado', store: 'Mercadona', category: 'Cereales y legumbres', kcal: 120, protein: 7.5, carbs: 16, fat: 2.5 },
  { name: 'Lentejas cocidas', brand: 'Hacendado', store: 'Mercadona', category: 'Cereales y legumbres', kcal: 105, protein: 8, carbs: 16, fat: 0.5 },
  { name: 'Alubias blancas cocidas', brand: 'Hacendado', store: 'Mercadona', category: 'Cereales y legumbres', kcal: 100, protein: 7, carbs: 15, fat: 0.5 },
  { name: 'Garbanzos cocidos', brand: 'Vitasia', store: 'Lidl', category: 'Cereales y legumbres', kcal: 122, protein: 7.6, carbs: 16.5, fat: 2.6 },
  { name: 'Lentejas cocidas', brand: 'Vitasia', store: 'Lidl', category: 'Cereales y legumbres', kcal: 103, protein: 7.8, carbs: 15.8, fat: 0.5 },

  // ---- Fruta y verdura ----
  { name: 'Plátano', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 89, protein: 1.1, carbs: 23, fat: 0.3 },
  { name: 'Manzana', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 52, protein: 0.3, carbs: 14, fat: 0.2 },
  { name: 'Plátano de Canarias', brand: 'Hacendado', store: 'Mercadona', category: 'Fruta y verdura', kcal: 89, protein: 1.1, carbs: 23, fat: 0.3 },
  { name: 'Naranja', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 47, protein: 0.9, carbs: 12, fat: 0.1 },
  { name: 'Fresas', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 32, protein: 0.7, carbs: 7.7, fat: 0.3 },
  { name: 'Arándanos', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 57, protein: 0.7, carbs: 14, fat: 0.3 },
  { name: 'Aguacate', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 160, protein: 2, carbs: 8.5, fat: 14.7 },
  { name: 'Tomate', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
  { name: 'Lechuga', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 15, protein: 1.4, carbs: 2.9, fat: 0.2 },
  { name: 'Pepino', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1 },
  { name: 'Zanahoria', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 41, protein: 0.9, carbs: 10, fat: 0.2 },
  { name: 'Brócoli', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 34, protein: 2.8, carbs: 7, fat: 0.4 },
  { name: 'Espinacas frescas', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  { name: 'Calabacín', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3 },
  { name: 'Pimiento rojo', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 31, protein: 1, carbs: 6, fat: 0.3 },
  { name: 'Cebolla', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 40, protein: 1.1, carbs: 9.3, fat: 0.1 },
  { name: 'Champiñones', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3 },
  { name: 'Judías verdes', brand: '', store: 'Genérico', category: 'Fruta y verdura', kcal: 31, protein: 1.8, carbs: 7, fat: 0.1 },
  { name: 'Verduras salteadas congeladas', brand: 'Hacendado', store: 'Mercadona', category: 'Fruta y verdura', kcal: 45, protein: 2, carbs: 7, fat: 0.8 },
  { name: 'Verduras salteadas congeladas', brand: 'Vitasia', store: 'Lidl', category: 'Fruta y verdura', kcal: 46, protein: 2.1, carbs: 7.2, fat: 0.9 },

  // ---- Snacks y frutos secos ----
  { name: 'Almendras crudas', brand: 'Hacendado', store: 'Mercadona', category: 'Snacks y frutos secos', kcal: 578, protein: 21, carbs: 6, fat: 50 },
  { name: 'Nueces', brand: 'Hacendado', store: 'Mercadona', category: 'Snacks y frutos secos', kcal: 654, protein: 15, carbs: 7, fat: 65 },
  { name: 'Anacardos tostados', brand: 'Hacendado', store: 'Mercadona', category: 'Snacks y frutos secos', kcal: 570, protein: 18, carbs: 27, fat: 44 },
  { name: 'Cacahuetes tostados', brand: 'Hacendado', store: 'Mercadona', category: 'Snacks y frutos secos', kcal: 590, protein: 25, carbs: 14, fat: 48 },
  { name: 'Crema de cacahuete', brand: 'Hacendado', store: 'Mercadona', category: 'Snacks y frutos secos', kcal: 620, protein: 24, carbs: 15, fat: 50 },
  { name: 'Mezcla de frutos secos y pasas', brand: 'Hacendado', store: 'Mercadona', category: 'Snacks y frutos secos', kcal: 480, protein: 14, carbs: 35, fat: 32 },
  { name: 'Barrita de cereales', brand: 'Hacendado', store: 'Mercadona', category: 'Snacks y frutos secos', kcal: 400, protein: 6, carbs: 65, fat: 13 },
  { name: 'Chocolate negro 85%', brand: 'Hacendado', store: 'Mercadona', category: 'Snacks y frutos secos', kcal: 585, protein: 9, carbs: 22, fat: 46 },
  { name: 'Palomitas de maíz', brand: 'Hacendado', store: 'Mercadona', category: 'Snacks y frutos secos', kcal: 480, protein: 9, carbs: 58, fat: 24 },
  { name: 'Almendras', brand: 'Alesto', store: 'Lidl', category: 'Snacks y frutos secos', kcal: 580, protein: 21, carbs: 5.5, fat: 51 },
  { name: 'Anacardos', brand: 'Alesto', store: 'Lidl', category: 'Snacks y frutos secos', kcal: 553, protein: 18, carbs: 26, fat: 43 },
  { name: 'Mantequilla de cacahuete', brand: 'Alesto', store: 'Lidl', category: 'Snacks y frutos secos', kcal: 605, protein: 25, carbs: 12, fat: 50 },
  { name: 'Barrita proteica', brand: 'Vamera', store: 'Lidl', category: 'Snacks y frutos secos', kcal: 370, protein: 30, carbs: 35, fat: 12 },

  // ---- Salsas, aceites y otros ----
  { name: 'Aceite de oliva virgen extra', brand: 'Hacendado', store: 'Mercadona', category: 'Salsas y aceites', kcal: 900, protein: 0, carbs: 0, fat: 100 },
  { name: 'Aceite de girasol', brand: 'Hacendado', store: 'Mercadona', category: 'Salsas y aceites', kcal: 900, protein: 0, carbs: 0, fat: 100 },
  { name: 'Mayonesa', brand: 'Hacendado', store: 'Mercadona', category: 'Salsas y aceites', kcal: 680, protein: 1, carbs: 2, fat: 75 },
  { name: 'Kétchup', brand: 'Hacendado', store: 'Mercadona', category: 'Salsas y aceites', kcal: 105, protein: 1.2, carbs: 24, fat: 0.3 },
  { name: 'Mostaza', brand: 'Hacendado', store: 'Mercadona', category: 'Salsas y aceites', kcal: 90, protein: 5, carbs: 8, fat: 4 },
  { name: 'Salsa de soja', brand: 'Hacendado', store: 'Mercadona', category: 'Salsas y aceites', kcal: 60, protein: 6, carbs: 6, fat: 0 },
  { name: 'Miel', brand: 'Hacendado', store: 'Mercadona', category: 'Salsas y aceites', kcal: 320, protein: 0.3, carbs: 78, fat: 0 },
  { name: 'Mermelada', brand: 'Hacendado', store: 'Mercadona', category: 'Salsas y aceites', kcal: 250, protein: 0.3, carbs: 61, fat: 0.1 },
  { name: 'Aceite de oliva virgen extra', brand: 'Rinderella', store: 'Lidl', category: 'Salsas y aceites', kcal: 900, protein: 0, carbs: 0, fat: 100 },
  { name: 'Kétchup', brand: 'Wetzel', store: 'Lidl', category: 'Salsas y aceites', kcal: 105, protein: 1.3, carbs: 24, fat: 0.2 },

  // ---- Bebidas ----
  { name: 'Agua mineral', brand: 'Hacendado', store: 'Mercadona', category: 'Bebidas', kcal: 0, protein: 0, carbs: 0, fat: 0 },
  { name: 'Zumo de naranja', brand: 'Hacendado', store: 'Mercadona', category: 'Bebidas', kcal: 45, protein: 0.7, carbs: 10, fat: 0.2 },
  { name: 'Bebida isotónica', brand: 'Hacendado', store: 'Mercadona', category: 'Bebidas', kcal: 26, protein: 0, carbs: 6.5, fat: 0 },
  { name: 'Café soluble', brand: 'Hacendado', store: 'Mercadona', category: 'Bebidas', kcal: 4, protein: 0.3, carbs: 0.5, fat: 0 },

  // ---- Suplementos ----
  { name: 'Proteína whey concentrada', brand: 'Hacendado (Foodspring)', store: 'Mercadona', category: 'Suplementos', kcal: 380, protein: 75, carbs: 8, fat: 6 },
  { name: 'Proteína whey', brand: 'Crownutrition', store: 'Lidl', category: 'Suplementos', kcal: 375, protein: 78, carbs: 6, fat: 5.5 },
  { name: 'Creatina monohidrato', brand: 'Genérico', store: 'Genérico', category: 'Suplementos', kcal: 0, protein: 0, carbs: 0, fat: 0 },
];
